from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:pk>/', views.product_detail_view, name='product_detail'),
    path('cart/add/<int:product_id>/', views.add_to_cart_view, name='add_to_cart'),
    path('shopping_cart/', views.shopping_cart_view, name='shopping_cart'),
    path('apply-coupon/', views.apply_coupon, name='apply_coupon'),
    path('remove-coupon/', views.remove_coupon, name='remove_coupon'),
    path('cart/remove/', views.remove_from_cart_view, name='remove_from_cart'),
    path('shop/', views.shop_all_products, name='shop_all'),
    path('shop/category/<int:category_id>/', views.shop_by_category, name='shop_by_category'),
    path('shop/brand/<int:brand_id>/', views.shop_by_brand, name='shop_by_brand'),
    path('shop/color/<str:color>/', views.shop_by_color, name='shop_by_color'),
    path('shop/size/<str:size>/', views.shop_by_size, name='shop_by_size'),
    path('shop/price/<int:min_price>/<int:max_price>/', views.shop_by_price, name='shop_by_price'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='orders_edit_profile'),
    path('contact/', views.landing_contact, name='landing_contact'),
    path('blog/', views.landing_blog, name='landing_blog'),
    path('blog/<slug:slug>/', views.landing_blog_detail, name='landing_blog_detail'),
    path('about-us/', views.landing_about_us, name='landing_about_us'),
    path('toggle-wishlist/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('buy-now/<int:pk>/', views.buy_now_view, name='buy_now'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('wishlist-preview/', views.wishlist_preview, name='wishlist_preview'),
    path('cart-preview/', views.cart_preview, name='cart_preview'),
    path('account/address/', views.account_address, name='account_address'),
    path('addresses/add/', views.add_address, name='add_address'),
    path('addresses/<int:pk>/delete/', views.delete_address, name='delete_address'),
    path('addresses/<int:pk>/edit/', views.edit_address, name='edit_address'),
    path('profile/', views.account_profile, name='account_profile'),
    path('faqs/', views.faqs_view, name='faqs'),
    path('shipping-policy/', views.shipping_policy_view, name='shipping_policy'),
    path('track-order/', views.track_order_view, name='track_order'),
    path('return_policy/', views.return_policy_view, name='return_policy'),

]
