# Generated by Django 5.2 on 2025-10-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
