# Generated by Django 5.2.4 on 2025-10-13 05:24

import eshop_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0010_product_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', eshop_app.models.CustomUserManager()),
            ],
        ),
    ]
