# Generated by Django 5.2 on 2025-10-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0013_remove_product_color_product_color_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Short description or introduction for the contact section')),
                ('branch1_name', models.CharField(max_length=100, verbose_name='Branch 1 Name')),
                ('branch1_address', models.CharField(max_length=255, verbose_name='Branch 1 Address')),
                ('branch1_phone', models.CharField(max_length=20, verbose_name='Branch 1 Phone')),
                ('branch1_email', models.EmailField(max_length=254, verbose_name='Branch 1 Email')),
                ('branch2_name', models.CharField(max_length=100, verbose_name='Branch 2 Name')),
                ('branch2_address', models.CharField(max_length=255, verbose_name='Branch 2 Address')),
                ('branch2_phone', models.CharField(max_length=20, verbose_name='Branch 2 Phone')),
                ('branch2_email', models.EmailField(max_length=254, verbose_name='Branch 2 Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
