# Generated by Django 5.2 on 2025-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0015_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
