# Generated by Django 5.2 on 2025-10-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0016_alter_blog_author_name_alter_blog_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are', models.TextField(blank=True, null=True)),
                ('who_we_do', models.TextField(blank=True, null=True)),
                ('why_choose_us', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
