# Generated by Django 5.2 on 2025-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0021_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set a fixed shipping cost for this product', max_digits=8),
        ),
    ]
