# Generated by Django 5.2 on 2025-10-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0022_product_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
