# Generated by Django 5.2 on 2025-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0023_product_is_free_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='colors',
            field=models.JSONField(blank=True, help_text='List of color names this image represents', null=True),
        ),
    ]
