# Generated by Django 5.2 on 2025-10-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0024_productmedia_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='colors',
        ),
    ]
