# Generated by Django 5.2 on 2025-10-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0025_remove_productmedia_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='created_at',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='color_name',
            field=models.CharField(blank=True, help_text="Associate this media with a product color (e.g., 'Black')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
