# Generated by Django 5.2 on 2025-10-28 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0026_remove_productmedia_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='color_name',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
    ]
