# Generated by Django 5.2 on 2025-10-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0027_remove_productmedia_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
