# Generated by Django 5.2 on 2025-10-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0028_productmedia_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'General FAQ',
                'verbose_name_plural': 'General FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
