# Generated by Django 5.2 on 2025-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0031_delete_productcategory_delete_productcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
